/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'finance',
    path: '/finance',
    component: 'layout.base',
    meta: {
      title: 'finance',
      i18nKey: 'route.finance',
      icon: 'mdi:currency-usd',
      order: 5
    },
    children: [
      {
        name: 'finance_commission',
        path: '/finance/commission',
        component: 'view.finance_commission',
        meta: {
          title: 'finance_commission',
          i18nKey: 'route.finance_commission'
        }
      },
      {
        name: 'finance_dashboard',
        path: '/finance/dashboard',
        component: 'view.finance_dashboard',
        meta: {
          title: 'finance_dashboard',
          i18nKey: 'route.finance_dashboard'
        }
      },
      {
        name: 'finance_ledger',
        path: '/finance/ledger',
        component: 'view.finance_ledger',
        meta: {
          title: 'finance_ledger',
          i18nKey: 'route.finance_ledger'
        }
      },
      {
        name: 'finance_withdrawal',
        path: '/finance/withdrawal',
        component: 'view.finance_withdrawal',
        meta: {
          title: 'finance_withdrawal',
          i18nKey: 'route.finance_withdrawal'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'marketing',
    path: '/marketing',
    component: 'layout.base',
    meta: {
      title: 'marketing',
      i18nKey: 'route.marketing'
    },
    children: [
      {
        name: 'marketing_asset',
        path: '/marketing/asset',
        component: 'view.marketing_asset',
        meta: {
          title: 'marketing_asset',
          i18nKey: 'route.marketing_asset'
        }
      },
      {
        name: 'marketing_template',
        path: '/marketing/template',
        component: 'view.marketing_template',
        meta: {
          title: 'marketing_template',
          i18nKey: 'route.marketing_template'
        }
      }
    ]
  },
  {
    name: 'member',
    path: '/member',
    component: 'layout.base',
    meta: {
      title: 'member',
      i18nKey: 'route.member'
    },
    children: [
      {
        name: 'member_upgrade',
        path: '/member/upgrade',
        component: 'view.member_upgrade',
        meta: {
          title: 'member_upgrade',
          i18nKey: 'route.member_upgrade'
        }
      }
    ]
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        },
        children: [
          {
            name: 'monitor_cache_list',
            path: '/monitor/cache/list',
            component: 'view.monitor_cache_list',
            meta: {
              title: 'monitor_cache_list',
              i18nKey: 'route.monitor_cache_list'
            }
          }
        ]
      },
      {
        name: 'monitor_job',
        path: '/monitor/job',
        component: 'view.monitor_job',
        meta: {
          title: 'monitor_job',
          i18nKey: 'route.monitor_job'
        }
      },
      {
        name: 'monitor_job-log',
        path: '/monitor/job-log',
        component: 'view.monitor_job-log',
        meta: {
          title: 'monitor_job-log',
          i18nKey: 'route.monitor_job-log'
        }
      },
      {
        name: 'monitor_logininfor',
        path: '/monitor/logininfor',
        component: 'view.monitor_logininfor',
        meta: {
          title: 'monitor_logininfor',
          i18nKey: 'route.monitor_logininfor'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      },
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      },
      {
        name: 'monitor_server',
        path: '/monitor/server',
        component: 'view.monitor_server',
        meta: {
          title: 'monitor_server',
          i18nKey: 'route.monitor_server'
        }
      }
    ]
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base',
    meta: {
      title: 'order',
      i18nKey: 'route.order',
      icon: 'mdi:cart-outline',
      order: 4
    },
    children: [
      {
        name: 'order_detail',
        path: '/order/detail',
        component: 'view.order_detail',
        meta: {
          title: 'order_detail',
          i18nKey: 'route.order_detail',
          hideInMenu: true
        }
      },
      {
        name: 'order_list',
        path: '/order/list',
        component: 'view.order_list',
        meta: {
          title: 'order_list',
          i18nKey: 'route.order_list'
        }
      }
    ]
  },
  {
    name: 'pms',
    path: '/pms',
    component: 'layout.base',
    meta: {
      title: 'pms',
      i18nKey: 'route.pms'
    },
    children: [
      {
        name: 'pms_attribute',
        path: '/pms/attribute',
        component: 'view.pms_attribute',
        meta: {
          title: 'pms_attribute',
          i18nKey: 'route.pms_attribute'
        }
      },
      {
        name: 'pms_brand',
        path: '/pms/brand',
        component: 'view.pms_brand',
        meta: {
          title: 'pms_brand',
          i18nKey: 'route.pms_brand'
        }
      },
      {
        name: 'pms_category',
        path: '/pms/category',
        component: 'view.pms_category',
        meta: {
          title: 'pms_category',
          i18nKey: 'route.pms_category'
        }
      },
      {
        name: 'pms_global-product',
        path: '/pms/global-product',
        component: 'view.pms_global-product',
        meta: {
          title: 'pms_global-product',
          i18nKey: 'route.pms_global-product'
        }
      },
      {
        name: 'pms_global-product-create',
        path: '/pms/global-product-create',
        component: 'view.pms_global-product-create',
        meta: {
          title: 'pms_global-product_create',
          i18nKey: 'route.pms_global-product_create',
          activeMenu: 'pms_global-product'
        }
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.blank$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'store',
    path: '/store',
    component: 'layout.base',
    meta: {
      title: 'store',
      i18nKey: 'route.store'
    },
    children: [
      {
        name: 'store_marketing',
        path: '/store/marketing',
        component: 'view.store_marketing',
        meta: {
          title: 'store_marketing',
          i18nKey: 'route.store_marketing'
        },
        children: [
          {
            name: 'store_marketing_activity',
            path: '/store/marketing/activity',
            component: 'view.store_marketing_activity',
            meta: {
              title: 'store_marketing_activity',
              i18nKey: 'route.store_marketing_activity'
            }
          },
          {
            name: 'store_marketing_distribution',
            path: '/store/marketing/distribution',
            component: 'view.store_marketing_distribution',
            meta: {
              title: 'store_marketing_distribution',
              i18nKey: 'route.store_marketing_distribution'
            }
          }
        ]
      },
      {
        name: 'store_product',
        path: '/store/product',
        meta: {
          title: 'store_product',
          i18nKey: 'route.store_product'
        },
        children: [
          {
            name: 'store_product_list',
            path: '/store/product/list',
            component: 'view.store_product_list',
            meta: {
              title: 'store_product_list',
              i18nKey: 'route.store_product_list'
            }
          },
          {
            name: 'store_product_market',
            path: '/store/product/market',
            component: 'view.store_product_market',
            meta: {
              title: 'store_product_market',
              i18nKey: 'route.store_product_market'
            }
          }
        ]
      },
      {
        name: 'store_stock',
        path: '/store/stock',
        component: 'view.store_stock',
        meta: {
          title: 'store_stock',
          i18nKey: 'route.store_stock'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_client',
        path: '/system/client',
        component: 'view.system_client',
        meta: {
          title: 'system_client',
          i18nKey: 'route.system_client'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_file-manager',
        path: '/system/file-manager',
        component: 'view.system_file-manager',
        meta: {
          title: 'system_file-manager',
          i18nKey: 'route.system_file-manager'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          localIcon: 'menu-tree-table',
          order: 4
        }
      },
      {
        name: 'system_message',
        path: '/system/message',
        component: 'view.system_message',
        meta: {
          title: 'system_message',
          i18nKey: 'route.system_message'
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_oss',
        path: '/system/oss',
        component: 'view.system_oss',
        meta: {
          title: 'system_oss',
          i18nKey: 'route.system_oss'
        }
      },
      {
        name: 'system_oss-config',
        path: '/system/oss-config',
        component: 'view.system_oss-config',
        meta: {
          title: 'system_oss-config',
          i18nKey: 'route.system_oss-config',
          constant: true,
          hideInMenu: true,
          icon: 'hugeicons:configuration-01'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_tenant-package',
        path: '/system/tenant-package',
        component: 'view.system_tenant-package',
        meta: {
          title: 'system_tenant-package',
          i18nKey: 'route.system_tenant-package'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      localIcon: 'menu-tool',
      order: 4
    },
    children: [
      {
        name: 'tool_build',
        path: '/tool/build',
        component: 'view.tool_build',
        meta: {
          title: 'tool_build',
          i18nKey: 'route.tool_build'
        }
      },
      {
        name: 'tool_gen',
        path: '/tool/gen',
        component: 'view.tool_gen',
        meta: {
          title: 'tool_gen',
          i18nKey: 'route.tool_gen',
          localIcon: 'menu-code',
          order: 2
        }
      },
      {
        name: 'tool_swagger',
        path: '/tool/swagger',
        component: 'view.tool_swagger',
        meta: {
          title: 'tool_swagger',
          i18nKey: 'route.tool_swagger'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  }
];
