/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'marketing',
    path: '/marketing',
    component: 'layout.base',
    meta: {
      title: 'marketing',
      i18nKey: 'route.marketing'
    },
    children: [
      {
        name: 'marketing_asset',
        path: '/marketing/asset',
        component: 'view.marketing_asset',
        meta: {
          title: 'marketing_asset',
          i18nKey: 'route.marketing_asset'
        }
      },
      {
        name: 'marketing_coupon',
        path: '/marketing/coupon',
        meta: {
          title: 'marketing_coupon',
          i18nKey: 'route.marketing_coupon'
        },
        children: [
          {
            name: 'marketing_coupon_template',
            path: '/marketing/coupon/template',
            component: 'view.marketing_coupon_template',
            meta: {
              title: 'marketing_coupon_template',
              i18nKey: 'route.marketing_coupon_template'
            }
          }
        ]
      },
      {
        name: 'marketing_course-attendance',
        path: '/marketing/course-attendance',
        component: 'view.marketing_course-attendance',
        meta: {
          title: 'marketing_course-attendance',
          i18nKey: 'route.marketing_course-attendance'
        }
      },
      {
        name: 'marketing_course-management',
        path: '/marketing/course-management',
        component: 'view.marketing_course-management',
        meta: {
          title: 'marketing_course-management',
          i18nKey: 'route.marketing_course-management'
        }
      },
      {
        name: 'marketing_course-schedule',
        path: '/marketing/course-schedule',
        component: 'view.marketing_course-schedule',
        meta: {
          title: 'marketing_course-schedule',
          i18nKey: 'route.marketing_course-schedule'
        }
      },
      {
        name: 'marketing_points',
        path: '/marketing/points',
        meta: {
          title: 'marketing_points',
          i18nKey: 'route.marketing_points'
        },
        children: [
          {
            name: 'marketing_points_accounts',
            path: '/marketing/points/accounts',
            component: 'view.marketing_points_accounts',
            meta: {
              title: 'marketing_points_accounts',
              i18nKey: 'route.marketing_points_accounts'
            }
          },
          {
            name: 'marketing_points_rules',
            path: '/marketing/points/rules',
            component: 'view.marketing_points_rules',
            meta: {
              title: 'marketing_points_rules',
              i18nKey: 'route.marketing_points_rules'
            }
          },
          {
            name: 'marketing_points_statistics',
            path: '/marketing/points/statistics',
            component: 'view.marketing_points_statistics',
            meta: {
              title: 'marketing_points_statistics',
              i18nKey: 'route.marketing_points_statistics'
            }
          },
          {
            name: 'marketing_points_tasks',
            path: '/marketing/points/tasks',
            component: 'view.marketing_points_tasks',
            meta: {
              title: 'marketing_points_tasks',
              i18nKey: 'route.marketing_points_tasks'
            }
          }
        ]
      },
      {
        name: 'marketing_statistics',
        path: '/marketing/statistics',
        meta: {
          title: 'marketing_statistics',
          i18nKey: 'route.marketing_statistics'
        },
        children: [
          {
            name: 'marketing_statistics_coupon',
            path: '/marketing/statistics/coupon',
            component: 'view.marketing_statistics_coupon',
            meta: {
              title: 'marketing_statistics_coupon',
              i18nKey: 'route.marketing_statistics_coupon'
            }
          }
        ]
      },
      {
        name: 'marketing_template',
        path: '/marketing/template',
        component: 'view.marketing_template',
        meta: {
          title: 'marketing_template',
          i18nKey: 'route.marketing_template'
        }
      }
    ]
  },
  {
    name: 'member',
    path: '/member',
    component: 'layout.base',
    meta: {
      title: 'member',
      i18nKey: 'route.member',
      icon: 'material-symbols:group-outline',
      order: 3
    },
    children: [
      {
        name: 'member_list',
        path: '/member/list',
        component: 'view.member_list',
        meta: {
          title: 'member_list',
          i18nKey: 'route.member_list',
          icon: 'material-symbols:list-alt-outline'
        }
      },
      {
        name: 'member_points-accounts',
        path: '/member/points-accounts',
        component: 'view.member_points-accounts',
        meta: {
          title: 'member_points-accounts',
          i18nKey: 'route.member_points-accounts'
        }
      },
      {
        name: 'member_upgrade',
        path: '/member/upgrade',
        component: 'view.member_upgrade',
        meta: {
          title: 'member_upgrade',
          i18nKey: 'route.member_upgrade',
          icon: 'material-symbols:unarchive-outline'
        }
      }
    ]
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        },
        children: [
          {
            name: 'monitor_cache_list',
            path: '/monitor/cache/list',
            component: 'view.monitor_cache_list',
            meta: {
              title: 'monitor_cache_list',
              i18nKey: 'route.monitor_cache_list'
            }
          }
        ]
      },
      {
        name: 'monitor_job',
        path: '/monitor/job',
        component: 'view.monitor_job',
        meta: {
          title: 'monitor_job',
          i18nKey: 'route.monitor_job'
        }
      },
      {
        name: 'monitor_job-log',
        path: '/monitor/job-log',
        component: 'view.monitor_job-log',
        meta: {
          title: 'monitor_job-log',
          i18nKey: 'route.monitor_job-log'
        }
      },
      {
        name: 'monitor_logininfor',
        path: '/monitor/logininfor',
        component: 'view.monitor_logininfor',
        meta: {
          title: 'monitor_logininfor',
          i18nKey: 'route.monitor_logininfor'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      },
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      },
      {
        name: 'monitor_server',
        path: '/monitor/server',
        component: 'view.monitor_server',
        meta: {
          title: 'monitor_server',
          i18nKey: 'route.monitor_server'
        }
      }
    ]
  },
  {
    name: 'pms',
    path: '/pms',
    component: 'layout.base',
    meta: {
      title: 'pms',
      i18nKey: 'route.pms'
    },
    children: [
      {
        name: 'pms_attribute',
        path: '/pms/attribute',
        component: 'view.pms_attribute',
        meta: {
          title: 'pms_attribute',
          i18nKey: 'route.pms_attribute'
        }
      },
      {
        name: 'pms_brand',
        path: '/pms/brand',
        component: 'view.pms_brand',
        meta: {
          title: 'pms_brand',
          i18nKey: 'route.pms_brand'
        }
      },
      {
        name: 'pms_category',
        path: '/pms/category',
        component: 'view.pms_category',
        meta: {
          title: 'pms_category',
          i18nKey: 'route.pms_category'
        }
      },
      {
        name: 'pms_global-product',
        path: '/pms/global-product',
        component: 'view.pms_global-product',
        meta: {
          title: 'pms_global-product',
          i18nKey: 'route.pms_global-product'
        }
      },
      {
        name: 'pms_global-product-create',
        path: '/pms/global-product-create',
        component: 'view.pms_global-product-create',
        meta: {
          title: 'pms_global-product_create',
          i18nKey: 'route.pms_global-product_create',
          activeMenu: 'pms_global-product'
        }
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.blank$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'store',
    path: '/store',
    component: 'layout.base',
    meta: {
      title: 'store',
      i18nKey: 'route.store',
      icon: 'mdi:store-outline',
      order: 4
    },
    children: [
      {
        name: 'store_distribution',
        path: '/store/distribution',
        component: 'view.store_distribution',
        meta: {
          title: 'store_distribution',
          i18nKey: 'route.store_distribution'
        },
        children: [
          {
            name: 'store_distribution_activity',
            path: '/store/distribution/activity',
            component: 'view.store_distribution_activity',
            meta: {
              title: 'store_distribution_activity',
              i18nKey: 'route.store_distribution_activity'
            }
          },
          {
            name: 'store_distribution_coupon-distribution',
            path: '/store/distribution/coupon-distribution',
            component: 'view.store_distribution_coupon-distribution',
            meta: {
              title: 'store_distribution_coupon-distribution',
              i18nKey: 'route.store_distribution_coupon-distribution'
            }
          },
          {
            name: 'store_distribution_coupon-usage',
            path: '/store/distribution/coupon-usage',
            component: 'view.store_distribution_coupon-usage',
            meta: {
              title: 'store_distribution_coupon-usage',
              i18nKey: 'route.store_distribution_coupon-usage'
            }
          },
          {
            name: 'store_distribution_distribution',
            path: '/store/distribution/distribution',
            component: 'view.store_distribution_distribution',
            meta: {
              title: 'store_distribution_distribution',
              i18nKey: 'route.store_distribution_distribution'
            }
          },
          {
            name: 'store_distribution_distribution-application',
            path: '/store/distribution/distribution-application',
            component: 'view.store_distribution_distribution-application',
            meta: {
              title: 'store_distribution_distribution-application',
              i18nKey: 'route.store_distribution_distribution-application'
            }
          },
          {
            name: 'store_distribution_distribution-dashboard',
            path: '/store/distribution/distribution-dashboard',
            component: 'view.store_distribution_distribution-dashboard',
            meta: {
              title: 'store_distribution_distribution-dashboard',
              i18nKey: 'route.store_distribution_distribution-dashboard'
            }
          },
          {
            name: 'store_distribution_distribution-level',
            path: '/store/distribution/distribution-level',
            component: 'view.store_distribution_distribution-level',
            meta: {
              title: 'store_distribution_distribution-level',
              i18nKey: 'route.store_distribution_distribution-level'
            }
          },
          {
            name: 'store_distribution_distribution-product',
            path: '/store/distribution/distribution-product',
            component: 'view.store_distribution_distribution-product',
            meta: {
              title: 'store_distribution_distribution-product',
              i18nKey: 'route.store_distribution_distribution-product'
            }
          }
        ]
      },
      {
        name: 'store_finance',
        path: '/store/finance',
        component: 'view.store_finance',
        meta: {
          title: 'store_finance',
          i18nKey: 'route.store_finance',
          icon: 'mdi:currency-usd'
        },
        children: [
          {
            name: 'store_finance_commission',
            path: '/store/finance/commission',
            component: 'view.store_finance_commission',
            meta: {
              title: 'store_finance_commission',
              i18nKey: 'route.store_finance_commission'
            }
          },
          {
            name: 'store_finance_dashboard',
            path: '/store/finance/dashboard',
            component: 'view.store_finance_dashboard',
            meta: {
              title: 'store_finance_dashboard',
              i18nKey: 'route.store_finance_dashboard'
            }
          },
          {
            name: 'store_finance_distribution-config',
            path: '/store/finance/distribution-config',
            component: 'view.store_finance_distribution-config',
            meta: {
              title: 'store_finance_distribution-config',
              i18nKey: 'route.store_finance_distribution-config'
            }
          },
          {
            name: 'store_finance_ledger',
            path: '/store/finance/ledger',
            component: 'view.store_finance_ledger',
            meta: {
              title: 'store_finance_ledger',
              i18nKey: 'route.store_finance_ledger'
            }
          },
          {
            name: 'store_finance_withdrawal',
            path: '/store/finance/withdrawal',
            component: 'view.store_finance_withdrawal',
            meta: {
              title: 'store_finance_withdrawal',
              i18nKey: 'route.store_finance_withdrawal'
            }
          }
        ]
      },
      {
        name: 'store_order',
        path: '/store/order',
        component: 'view.store_order',
        meta: {
          title: 'store_order',
          i18nKey: 'route.store_order',
          icon: 'mdi:cart-outline'
        },
        children: [
          {
            name: 'store_order_detail',
            path: '/store/order/detail',
            component: 'view.store_order_detail',
            meta: {
              title: 'store_order_detail',
              i18nKey: 'route.store_order_detail',
              hideInMenu: true
            }
          },
          {
            name: 'store_order_dispatch',
            path: '/store/order/dispatch',
            component: 'view.store_order_dispatch',
            meta: {
              title: 'store_order_dispatch',
              i18nKey: 'route.store_order_dispatch'
            }
          },
          {
            name: 'store_order_list',
            path: '/store/order/list',
            component: 'view.store_order_list',
            meta: {
              title: 'store_order_list',
              i18nKey: 'route.store_order_list'
            }
          }
        ]
      },
      {
        name: 'store_product',
        path: '/store/product',
        meta: {
          title: 'store_product',
          i18nKey: 'route.store_product'
        },
        children: [
          {
            name: 'store_product_list',
            path: '/store/product/list',
            component: 'view.store_product_list',
            meta: {
              title: 'store_product_list',
              i18nKey: 'route.store_product_list'
            }
          },
          {
            name: 'store_product_market',
            path: '/store/product/market',
            component: 'view.store_product_market',
            meta: {
              title: 'store_product_market',
              i18nKey: 'route.store_product_market'
            }
          }
        ]
      },
      {
        name: 'store_stock',
        path: '/store/stock',
        component: 'view.store_stock',
        meta: {
          title: 'store_stock',
          i18nKey: 'route.store_stock'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_client',
        path: '/system/client',
        component: 'view.system_client',
        meta: {
          title: 'system_client',
          i18nKey: 'route.system_client'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_file-manager',
        path: '/system/file-manager',
        component: 'view.system_file-manager',
        meta: {
          title: 'system_file-manager',
          i18nKey: 'route.system_file-manager'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          localIcon: 'menu-tree-table',
          order: 4
        }
      },
      {
        name: 'system_message',
        path: '/system/message',
        component: 'view.system_message',
        meta: {
          title: 'system_message',
          i18nKey: 'route.system_message'
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_oss',
        path: '/system/oss',
        component: 'view.system_oss',
        meta: {
          title: 'system_oss',
          i18nKey: 'route.system_oss'
        }
      },
      {
        name: 'system_oss-config',
        path: '/system/oss-config',
        component: 'view.system_oss-config',
        meta: {
          title: 'system_oss-config',
          i18nKey: 'route.system_oss-config',
          constant: true,
          hideInMenu: true,
          icon: 'hugeicons:configuration-01'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_tenant-package',
        path: '/system/tenant-package',
        component: 'view.system_tenant-package',
        meta: {
          title: 'system_tenant-package',
          i18nKey: 'route.system_tenant-package'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      localIcon: 'menu-tool',
      order: 4
    },
    children: [
      {
        name: 'tool_build',
        path: '/tool/build',
        component: 'view.tool_build',
        meta: {
          title: 'tool_build',
          i18nKey: 'route.tool_build'
        }
      },
      {
        name: 'tool_gen',
        path: '/tool/gen',
        component: 'view.tool_gen',
        meta: {
          title: 'tool_gen',
          i18nKey: 'route.tool_gen',
          localIcon: 'menu-code',
          order: 2
        }
      },
      {
        name: 'tool_swagger',
        path: '/tool/swagger',
        component: 'view.tool_swagger',
        meta: {
          title: 'tool_swagger',
          i18nKey: 'route.tool_swagger'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  }
];
