packages:
  - 'apps/*'
  - 'apps/admin-web/packages/*'
  - 'libs/*'
  - 'docs'

catalog:
  # TypeScript
  typescript: '5.8.3'

  # 运行时共享
  dayjs: '1.11.19'
  axios: '1.12.2'
  vue: '3.5.24'
  vue-router: '4.6.3'
  pinia: '3.0.4'
  vue-i18n: '9.14.2'

  # 开发工具共享
  '@types/node': '22.15.0'
  eslint: '9.39.1'
  prettier: '3.3.3'

  # 测试
  vitest: '2.1.9'

  # Git hooks
  simple-git-hooks: '2.13.1'
  lint-staged: '15.2.10'
  '@commitlint/cli': '19.8.1'
  '@commitlint/config-conventional': '19.8.1'
