/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "exception": "/exception";
    "exception_403": "/exception/403";
    "exception_404": "/exception/404";
    "exception_500": "/exception/500";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "finance": "/finance";
    "finance_commission": "/finance/commission";
    "finance_dashboard": "/finance/dashboard";
    "finance_distribution-config": "/finance/distribution-config";
    "finance_ledger": "/finance/ledger";
    "finance_withdrawal": "/finance/withdrawal";
    "home": "/home";
    "iframe-page": "/iframe-page/:url";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "marketing": "/marketing";
    "marketing_asset": "/marketing/asset";
    "marketing_coupon": "/marketing/coupon";
    "marketing_coupon_template": "/marketing/coupon/template";
    "marketing_course-attendance": "/marketing/course-attendance";
    "marketing_course-management": "/marketing/course-management";
    "marketing_course-schedule": "/marketing/course-schedule";
    "marketing_points": "/marketing/points";
    "marketing_points_accounts": "/marketing/points/accounts";
    "marketing_points_rules": "/marketing/points/rules";
    "marketing_points_statistics": "/marketing/points/statistics";
    "marketing_points_tasks": "/marketing/points/tasks";
    "marketing_statistics": "/marketing/statistics";
    "marketing_statistics_coupon": "/marketing/statistics/coupon";
    "marketing_template": "/marketing/template";
    "member": "/member";
    "member_list": "/member/list";
    "member_points-accounts": "/member/points-accounts";
    "member_upgrade": "/member/upgrade";
    "monitor": "/monitor";
    "monitor_cache": "/monitor/cache";
    "monitor_cache_list": "/monitor/cache/list";
    "monitor_job": "/monitor/job";
    "monitor_job-log": "/monitor/job-log";
    "monitor_logininfor": "/monitor/logininfor";
    "monitor_online": "/monitor/online";
    "monitor_operlog": "/monitor/operlog";
    "monitor_server": "/monitor/server";
    "order": "/order";
    "order_detail": "/order/detail";
    "order_list": "/order/list";
    "pms": "/pms";
    "pms_attribute": "/pms/attribute";
    "pms_brand": "/pms/brand";
    "pms_category": "/pms/category";
    "pms_global-product": "/pms/global-product";
    "pms_global-product-create": "/pms/global-product-create";
    "social-callback": "/social-callback";
    "store": "/store";
    "store_marketing": "/store/marketing";
    "store_marketing_activity": "/store/marketing/activity";
    "store_marketing_coupon-distribution": "/store/marketing/coupon-distribution";
    "store_marketing_coupon-usage": "/store/marketing/coupon-usage";
    "store_marketing_distribution": "/store/marketing/distribution";
    "store_product": "/store/product";
    "store_product_list": "/store/product/list";
    "store_product_market": "/store/product/market";
    "store_stock": "/store/stock";
    "system": "/system";
    "system_client": "/system/client";
    "system_config": "/system/config";
    "system_dept": "/system/dept";
    "system_dict": "/system/dict";
    "system_file-manager": "/system/file-manager";
    "system_menu": "/system/menu";
    "system_message": "/system/message";
    "system_notice": "/system/notice";
    "system_oss": "/system/oss";
    "system_oss-config": "/system/oss-config";
    "system_post": "/system/post";
    "system_role": "/system/role";
    "system_tenant": "/system/tenant";
    "system_tenant-package": "/system/tenant-package";
    "system_user": "/system/user";
    "tool": "/tool";
    "tool_build": "/tool/build";
    "tool_gen": "/tool/gen";
    "tool_swagger": "/tool/swagger";
    "user-center": "/user-center";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "exception_403"
    | "exception_404"
    | "exception_500"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "finance"
    | "home"
    | "iframe-page"
    | "login"
    | "marketing"
    | "member"
    | "monitor"
    | "order"
    | "pms"
    | "social-callback"
    | "store"
    | "system"
    | "tool"
    | "user-center"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "social-callback"
    | "user-center"
    | "finance_commission"
    | "finance_dashboard"
    | "finance_distribution-config"
    | "finance_ledger"
    | "finance_withdrawal"
    | "home"
    | "marketing_asset"
    | "marketing_coupon_template"
    | "marketing_course-attendance"
    | "marketing_course-management"
    | "marketing_course-schedule"
    | "marketing_points_accounts"
    | "marketing_points_rules"
    | "marketing_points_statistics"
    | "marketing_points_tasks"
    | "marketing_statistics_coupon"
    | "marketing_template"
    | "member_list"
    | "member_points-accounts"
    | "member_upgrade"
    | "monitor_cache"
    | "monitor_cache_list"
    | "monitor_job-log"
    | "monitor_job"
    | "monitor_logininfor"
    | "monitor_online"
    | "monitor_operlog"
    | "monitor_server"
    | "order_detail"
    | "order_list"
    | "pms_attribute"
    | "pms_brand"
    | "pms_category"
    | "pms_global-product-create"
    | "pms_global-product"
    | "store_marketing_activity"
    | "store_marketing_coupon-distribution"
    | "store_marketing_coupon-usage"
    | "store_marketing_distribution"
    | "store_marketing"
    | "store_product_list"
    | "store_product_market"
    | "store_stock"
    | "system_client"
    | "system_config"
    | "system_dept"
    | "system_dict"
    | "system_file-manager"
    | "system_menu"
    | "system_message"
    | "system_notice"
    | "system_oss-config"
    | "system_oss"
    | "system_post"
    | "system_role"
    | "system_tenant-package"
    | "system_tenant"
    | "system_user"
    | "tool_build"
    | "tool_gen"
    | "tool_swagger"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception_403"
    | "exception_404"
    | "exception_500"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;

  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
